### ISSUE TITLE
Generator missing dependency

### ISSUE THREAD

**Issue by daltonamitchell** [DockYard/ember-cli-custom-assertions#13]
Just tried to run `ember g assertion contains` and I get the following error: 

``` sh
Cannot find module 'ember-cli/lib/utilities/string'
Error: Cannot find module 'ember-cli/lib/utilities/string'
...
```

I notice in `blueprints/assertion/index.js` the first line requires that module

``` js
var stringUtil = require('ember-cli/lib/utilities/string');
```

but digging through `node_modules`, I don't actually see that file. Could this be a version mismatch issue? Here's the output of `ember v`:

``` sh
ember-cli: 2.4.3
node: 5.3.0
os: darwin x64
```

**Comment by patrickberkeley** [comment]
This was fixed here https://github.com/DockYard/ember-cli-custom-assertions/pull/15, we just need a new release.

**Comment by san650** [comment]
Just installed the latest (pubilshed) version and I'm having this same issue. Are you planning on releasing v0.0.6 to npmjs?

Right now the latest version on npmjs is v0.0.5

**Comment by cibernox** [comment]
I believe this can be closed now
