### ISSUE TITLE
0.0.6/0.1.0 not published into NPM

### ISSUE THREAD

**Issue by cibernox** [DockYard/ember-cli-custom-assertions#19]
Something weird happened during the last update, but the last releases are not available in NPM. The last version in NPM is 0.0.5

**Comment by bcardarella** [comment]
Not sure what happened. I'll publish now.

**Comment by bcardarella** [comment]
Done!

**Comment by cibernox** [comment]
That is fast service, sir! 👏 👏 👏

**Comment by bcardarella** [comment]
I don't have a life 🍼

**Comment by cibernox** [comment]
Here is also Saturday 😭
