### ISSUE TITLE
Doesn't work from within addons

### ISSUE THREAD

**Issue by cibernox** [DockYard/ember-cli-custom-assertions#21]
## Version
ember-cli: 2.9.0-beta.2
node: 6.6.0
os: darwin x64
ember-cli-custom-assertions: 0.0.6

## Test Case
Not really a test case. 
https://github.com/DockYard/ember-cli-custom-assertions/issues/new

## Steps to reproduce
Install it in an empty addon and try to run `ember g assertion is-cool`.

## Expected Behavior
An assertion is generated

## Actual Behavior
Error: `Cannot find module 'ember-cli-string-utils'`

Given that I use this addon in apps without problem, seems the issue arises when used from within another addon.

**Comment by bcardarella** [comment]
@cibernox looks like the rendered blueprints are requiring them: https://github.com/DockYard/ember-cli-custom-assertions/blob/25aa046ff5a25b6df23ebe3e94f2e07e380db244/blueprints/assertion/index.js#L1

If you wanted to add that addon into the `dependencies` object in `package.json` I can do a release
