### ISSUE TITLE
Importing assertionInjector disables the whole test module

### ISSUE THREAD

**Issue by lolmaus** [DockYard/ember-cli-custom-assertions#8]
Simply doing 

```
import { assertionInjector } from '../assertions';
```

results in the whole module disappearing from QUnit test results.

![Imgur](http://i.imgur.com/KxozY14.jpg)

**Comment by bcardarella** [comment]
@lolmaus what version of ember-cli are you using? This is clearly bad

**Comment by lolmaus** [comment]
Ember CLI 1.13.8
Ember 2.1.0-beta.2
ember-qunit 0.4.10
qunit 1.19.0
ember-cli-qunit 1.0.1

**Comment by bcardarella** [comment]
Thank you, I'll try updating our test suite for that set. Will report back soon

**Comment by lolmaus** [comment]
:bow:

**Comment by rwjblue** [comment]
It might be an invalid import which would result in an error when the test modules are loaded, but ith your ember-cli-qunit version this error should be notated with a failing test (this is done [here](https://github.com/ember-cli/ember-cli-qunit/blob/master/vendor/ember-cli-qunit/test-loader.js#L9-L14)).

**Comment by lolmaus** [comment]
@rwjblue You're right:

> TestLoader Failures: exam-sim-ember/tests/unit/models/exam-session-test: could not be loaded
> Error: Could not find module `exam-sim-ember/tests/unit/assertions`

I'm doing `import { assertionInjector } from '../assertions';`.

This doesn't look right, but so does [this](https://github.com/dockyard/ember-cli-custom-assertions/blob/master/tests/unit/custom-assertion-test.js#L2).

**Comment by rwjblue** [comment]
Seems correct to me.

You added one extra level since your test is at `tests/unit/models/exam-session-test.js`, you would need to `import { assertionInjector } from '../../assertions';`.

**Comment by rwjblue** [comment]
You could also use `import { assertionInjector } from '<your app name>/tests/assertions';` if you didn't want to deal with the annoyance of the tracking down the right number of `../` to add when importing.

**Comment by rwjblue** [comment]
As an aside, I'm pretty happy that ember-cli-qunit is giving you **exactly** what you need to fix this via a failing test.  For quite a while errors thrown while evaluating the module (like invalid imports) caused the whole test module to be completely ignored with no indication of any failure.

**Comment by lolmaus** [comment]
It didn't help me because there was no `assertions` file at that path, so it was pretty magical to me.
